version: "3"
services:
  smoodle:
    image: smoodle
    build:
      context: ./
      args:
        node_version: 13.7.0
        elixir_version: 1.10.0
    ports:
      - "4001:4000"
    environment:
      DATABASE_URL: postgresql://smoodle:secret@db:5432/smoodle
      SCHEME: http
      HOST_NAME: localhost
      PORT: 4001
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: smoodle
    ports:
      - "5433:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
volumes:
  data:
